# Generated by Django 5.0.6 on 2024-05-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0002_alter_customuser_background_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
