# Generated by Django 5.0.6 on 2024-05-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='treners',
            name='staff',
            field=models.CharField(choices=[('trener', 'Trener'), ('director', 'Director'), ('user', 'User'), ('manager', 'Manager')], default=-1, max_length=20),
            preserve_default=False,
        ),
    ]
